### ISSUE TITLE
docker startup Error!!

### ISSUE THREAD

**Issue by Flavia-de-Luce** [Summit-Sync/backend#47]
Ich habe mir heute 03.06. den neusten Docker Container gezogen und wenn ich ihn starte wird folgende Execption ausgelöst:

`api-1    | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'participantService' defined in URL [jar:nested:/summit-sync/summit-sync-0.0.1-SNAPSHOT.jar/!BOO
T-INF/classes/!/com/summitsync/api/participant/ParticipantService.class]: Unsatisfied dependency expressed through constructor parameter 3: Error creating bean with name 'keycloakRestService': Injection of autowired dependencies failed`

Rest des Stacktraces:

`api-1    |      at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354) ~[spring-beans-6.1.3.jar!/:6.1.3]        
api-1    |      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:959) ~[spring-context-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.2.jar!/:3.2.2]
api-1    |      at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.2.jar!/:3.2.2]
api-1    |      at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.2.jar!/:3.2.2]
api-1    |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.2.jar!/:3.2.2]
api-1    |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.2.jar!/:3.2.2]
api-1    |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.2.jar!/:3.2.2]
api-1    |      at com.summitsync.api.SummitSyncApplication.main(SummitSyncApplication.java:14) ~[!/:0.0.1-SNAPSHOT]
api-1    |      at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
api-1    |      at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
api-1    |      at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91) ~[summit-sync-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
api-1    |      at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53) ~[summit-sync-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
api-1    |      at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58) ~[summit-sync-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
api-1    | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'keycloakRestService': Injection of autowired dependencies failed
api-1    |      at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:514) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1418) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:907) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:785) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      ... 24 common frames omitted
api-1    | Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'KEYCLOAK_SYSTEM_USER_CLIENT_ID' in value "${KEYCLOAK_SYSTEM_USER_CLIENT_ID}"
api-1    |      at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:145) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:508) ~[spring-beans-6.1.3.jar!/:6.1.3]api-1    |      at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:145) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:508) ~[spring-beans-6.1.3.jar!/:6.1.3]api-1    |      at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:145) ~[spring-beans-6.1.3.jar!/:6.1.3]
api-1    |      at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:508) ~[spring-beans-6.1.3.jar!/:6.1.3]api-1    |      ... 36 common frames omitted
api-1    |
api-1 exited with code 1`

**Comment by Flavia-de-Luce** [comment]
Durch erweitern der docker-compose.yml gelöst!
Änderungen:

`
api:
  environment:
      - KEYCLOAK_SYSTEM_USER_CLIENT_ID=summit-sync-backend-system-user
      - KEYCLOAK_SYSTEM_USER_PASSWORD=KMy5FqqXWMmzycFNXx5Fl0D7t5ftSsn`
